# Generated by Django 5.2 on 2025-04-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completed',
        ),
    ]
